alta:
  title: hello123
  description: 美好的生活
KK:
spring:
  datasource:
    url: jdbc:mysql://10.10.40.253:3306/test?useServerPrepStmts=true&cachePrepStmts=true&setUnicode=true&characterEncoding=UTF-8&autoReconnectForPools=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 3