alta:
  title: hello123
  description: 美好的生活
KK:
spring:
  datasource:
    url: jdbc:mysql://cn-synative.cgh7hlxi6jrk.rds.cn-north-1.amazonaws.com.cn:33060/support?useServerPrepStmts=true&cachePrepStmts=true&setUnicode=true&characterEncoding=UTF-8&autoReconnectForPools=true&serverTimezone=UTC
    username: app
    password: App@170905
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 3