alta:
  title: hello123
  description: 美好的生活
KK:
spring:
  datasource:
    url: jdbc:mysql://10.10.40.253:3306/test?useServerPrepStmts=true&cachePrepStmts=true&setUnicode=true&characterEncoding=UTF-8&autoReconnectForPools=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 3
mqtt:
  serverName: NasManager_
  host: tcp://10.10.40.227:1883
  clientId: 1021
  qos: 2
  tmpDir: C:/log
  retained: false
  options:
    connectiontimeout: 30
    automaticReconnect: true
    keepAliveInterval: 60
    cleanSession: false
    maxinflight: 100
    userName: php
    password: phpmq@123!
  bufferOptions:
    bufferSize: 1000
    bufferEnabled: true
    persistBuffer: false
    deleteOldestMessages: false